baseURL = "https://tcelik.42.fr/info"
theme = "shell"
paginate = 8
canonifyURLs = true

[params]

 [Params.Terminal]
  schema = "gruvbox_dark"

 userName = "tcelik"
 pcName = "42"
 workDir = "me"

 description = """
 Hi...
 I Am Taha ÇELİK
 This is My Portfolio!
 """

 [Params.Tree]
 use = true
 files = [
 ["C", ""],
 ["C++", ""],
 ["SQL", ""],
 ["Java", ""],
 ["Docker", ""],
 ]
