CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'tcelik'@'%' IDENTIFIED BY '14159265';
GRANT ALL PRIVILEGES ON wordpress.* TO 'tcelik'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'PI.14159265';
